version: "3.9"
services:
  app:
    volumes:
      - ./src:/myapp/src
      - ./Cargo.lock:/myapp/Cargo.lock
      - ./Cargo.toml:/myapp/Cargo.toml
    build:
      context: .
      dockerfile: ./docker/Dockerfile

volumes:
  data: